var feeds=[];const sortByDateBtn=document.getElementById("sortByDateBtn"),sortByTitleBtn=document.getElementById("sortByTitleBtn"),sortByURLBtn=document.getElementById("sortByUrlBtn"),sortByDescriptionBtn=document.getElementById("sortByDescriptionBtn"),sortByCategoriesBtn=document.getElementById("sortByCategoriesBtn"),updateNewsBtn=document.getElementById("updateNewsBtn"),addUrlBtn=document.getElementById("addUrlBtn"),searchNewsBtn=document.getElementById("btnSearch");
sortByDateBtn.addEventListener("click",()=>sortColumn(0));sortByTitleBtn.addEventListener("click",()=>sortColumn(1));sortByURLBtn.addEventListener("click",()=>sortColumn(2));sortByDescriptionBtn.addEventListener("click",()=>sortColumn(3));sortByCategoriesBtn.addEventListener("click",()=>sortColumn(4));updateNewsBtn.addEventListener("click",actualizarNoticias);addUrlBtn.addEventListener("click",addUrl);searchNewsBtn.addEventListener("click",searchNews);
function addUrl(){var a=document.getElementById("feedUrl").value;""!==a.trim()&&!feeds.includes(a.trim())&&isUrl(a)?(feeds.push(a),urlAdd(a),document.getElementById("feedUrl").value=""):alert("La URL ingresada no es v\u00e1lida")}function urlAdd(a){var c=document.querySelector(".linksadded"),b=document.createElement("p");b.textContent=a;c.appendChild(b)}
function actualizarNoticias(){var a=new XMLHttpRequest;a.onreadystatechange=function(){if(4==this.readyState&&200==this.status){var b=JSON.parse(this.responseText);0<b.length?fillTable(b):document.getElementById("tableFeeds").innerHTML="0 Resultados"}};var c=feeds.map(b=>"urls[]="+encodeURIComponent(b)).join("&");a.open("GET","read_feed.php?"+c);a.send()}
function searchNews(){var a=document.getElementById("searchNews").value.toLowerCase(),c=new XMLHttpRequest;c.onreadystatechange=function(){if(4==this.readyState&&200==this.status){var b=JSON.parse(this.responseText);0<b.length?fillTable(b):document.getElementById("tableFeeds").innerHTML="0 Resultados"}};c.open("GET","search_feed.php?searchString="+encodeURIComponent(a));c.send()}
function fillTable(a){var c="";a.forEach(function(b){c+="<tr><td><h2>Fecha:<span class='fecha'>"+b.date+"</span></h2><br><h1><span class='titulo'>"+b.title+"</span></h1><br><h2>URL:</h2> <a href='"+b.url+"'><span class='url'>"+b.url+"</span></a><br><h2>Descripci\u00f3n:</h2> <span class='descripcion'>"+b.description+"</span><br><h2>Categor\u00edas:</h2> <br><span class='categoria'>"+b.category+"</span><br></td><td>";c=null!==b.image_url&&"undefined"!==typeof b.image_url?c+("<img src='"+b.image_url+
"' alt='imagen' class='newsImage' style='max-width: 100%; height: auto;' loading='lazy'>"):c+"<img src='no_image.jpg' alt='imagen predeterminada' class='newsImage' style='max-width: 100%; height: auto;'>";c+="</td><tr>"});document.getElementById("tableFeeds").innerHTML=c}function isUrl(a){try{return new URL(a),!0}catch(c){return!1}}function byDate(){sortColumn(0)}function byTitle(){sortColumn(1)}function byURL(){sortColumn(2)}function byDescription(){sortColumn(3)}
function byCategories(){sortColumn(4)}
function sortColumn(a){let c=document.querySelectorAll(".table tbody tr");c=Array.from(c).filter(d=>""!==d.innerHTML.trim());c.sort(function(d,e){let g;if(0===a){if(d=d.querySelector(".fecha"),e=e.querySelector(".fecha"),d&&e){var f=new Date(d.textContent.trim());g=new Date(e.textContent.trim())}}else 1===a?(d.querySelector(".titulo").textContent.trim().toLowerCase(),f=d.querySelector(".titulo").textContent.trim().toLowerCase(),g=e.querySelector(".titulo").textContent.trim().toLowerCase()):2===a?
(f=d.querySelector(".url").textContent.trim().toLowerCase(),g=e.querySelector(".url").textContent.trim().toLowerCase()):3===a?(f=d.querySelector(".descripcion").textContent.trim().toLowerCase(),g=e.querySelector(".descripcion").textContent.trim().toLowerCase()):4===a&&(f=d.querySelectorAll(".categoria"),e=e.querySelectorAll(".categoria"),f=0<f.length?f[0].textContent.trim().toLowerCase():"",g=0<e.length?e[0].textContent.trim().toLowerCase():"");return 0===a?g-f:f.localeCompare(g)});let b=document.querySelector(".table tbody");
for(;b.firstChild;)b.removeChild(b.firstChild);c.forEach(function(d){b.appendChild(d)})}document.addEventListener("DOMContentLoaded",function(){getNoticias()});function getNoticias(){var a=new XMLHttpRequest;a.onreadystatechange=function(){if(4==this.readyState&&200==this.status){var c=JSON.parse(this.responseText);0<c.length?fillTable(c):document.getElementById("tableFeeds").innerHTML="0 Resultados"}};a.open("GET","load_feed.php");a.send()};
